/**
 * @generated by scripts/gen-types.mjs from web/openapi.json. DO NOT EDIT.
 * Regenerate with `make types` (or `npm run types`) after `make openapi`.
 */

export interface paths {
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Results */
        get: operations["get_eval_results_eval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replays */
        get: operations["get_replays_replays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replays/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay */
        get: operations["get_replay_replays__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{thread_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_runs__thread_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{thread_id}/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiments */
        get: operations["get_experiments_runs__thread_id__experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{thread_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_runs__thread_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityEvent */
        ActivityEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "node" | "interrupt" | "done" | "error";
            /** Node */
            node: string | null;
            /** Seq */
            seq: number;
            /** Spent Usd */
            spent_usd: number | null;
            /** Summary */
            summary: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /**
         * AttemptRecord
         * @description M9d: one self-debug attempt (SPEC: "runner self-debug max k=3"), for the operator
         *     console's experiment drawer `attempts` tab — "attempt 1 failed, 2 failed, 3 succeeded, each
         *     with its error and what changed". `outcome` mirrors the three ways
         *     foundry/teams/experiment_runner.py's loop can end an attempt: a non-zero sandbox exit
         *     (`failed_execution`), an exit-0 run whose stdout has no parseable FOUNDRY_METRICS line
         *     (`failed_metrics`), or a clean parse (`success`).
         */
        AttemptRecord: {
            /** Attempt */
            attempt: number;
            /** Code */
            code: string;
            /** Error */
            error: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "success" | "failed_execution" | "failed_metrics";
            /** Stderr */
            stderr: string;
            /** Stdout */
            stdout: string;
        };
        /**
         * AuditEvidence
         * @description M9d: the code-measured numbers behind one RedTeamFinding, carried as real fields rather
         *     than embedded in `explanation` prose — CLAUDE.md's "metrics computed by code, never estimated
         *     by an LLM" applies to what the operator console renders too. Built from the same
         *     foundry/tools/audit.py AuditReport (via foundry/teams/red_team.py's RedTeamContext) that
         *     `_apply_floor` already reads; attached to every finding a pass produces, `valid` verdicts
         *     included, since the measurement is what justifies a clearing verdict too. `worst_column` /
         *     `worst_column_target_auc` are None only when the audit found no column with a measurable
         *     target association (foundry/tools/audit.py: a non-numeric multiclass target has no median
         *     split, so every column's target_auc stays None).
         */
        AuditEvidence: {
            /** Duplicate Row Rate */
            duplicate_row_rate: number;
            /** Reported Metric Name */
            reported_metric_name: string;
            /** Reported Metric Value */
            reported_metric_value: number;
            /** Worst Column */
            worst_column: string | null;
            /** Worst Column Target Auc */
            worst_column_target_auc: number | null;
        };
        /**
         * ColumnProfile
         * @description Assembled by foundry/teams/data_team.py from RawColumnStats (measured) plus the LLM's
         *     ProfileAssessment (which columns are potential leaks) — never returned directly by
         *     llm.structured(), so it is never registered in StubClient's schema registry.
         */
        ColumnProfile: {
            /** Dtype */
            dtype: string;
            /**
             * Is Potential Leak
             * @default false
             */
            is_potential_leak: boolean;
            /** N Missing */
            n_missing: number;
            /** N Unique */
            n_unique: number;
            /** Name */
            name: string;
            /** Pct Missing */
            pct_missing: number;
        };
        /** DataProfile */
        DataProfile: {
            /** Columns */
            columns: components["schemas"]["ColumnProfile"][];
            /** N Cols */
            n_cols: number;
            /** N Rows */
            n_rows: number;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Target Column */
            target_column: string;
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "binary_classification" | "multiclass_classification" | "regression";
        };
        /**
         * DatasetOption
         * @description M9e: what the console's start-a-run panel needs to populate its dataset select
         *     (docs/design-plan.md §6) — deliberately NOT DatasetSpec itself, which carries `path`, a host
         *     filesystem path the API must never publish.
         */
        DatasetOption: {
            /** Description */
            description: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Primary Metric
             * @enum {string}
             */
            primary_metric: "roc_auc" | "accuracy" | "f1" | "rmse";
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "binary_classification" | "multiclass_classification" | "regression";
        };
        /** ExperimentResult */
        ExperimentResult: {
            /** Attempt History */
            attempt_history: components["schemas"]["AttemptRecord"][];
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /**
             * Code
             * @default
             */
            code: string;
            /** Cost Usd */
            cost_usd: number;
            /** Duration S */
            duration_s: number;
            /** Error */
            error: string | null;
            /** Experiment Id */
            experiment_id: string;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Mlflow Run Id */
            mlflow_run_id: string | null;
            spec: components["schemas"]["ExperimentSpec"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "failed";
            /**
             * Stderr
             * @default
             */
            stderr: string;
            /**
             * Stdout
             * @default
             */
            stdout: string;
        };
        /** ExperimentSpec */
        ExperimentSpec: {
            /** Est Cost Usd */
            est_cost_usd: number;
            /** Experiment Id */
            experiment_id: string;
            /** Hyperparams */
            hyperparams: {
                [key: string]: number | string | boolean;
            };
            /**
             * Model Family
             * @enum {string}
             */
            model_family: "logistic_regression" | "random_forest" | "gradient_boosting" | "xgboost" | "lightgbm" | "mlp";
            /** Rationale */
            rationale: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Experiment Id */
            experiment_id: string;
            /** Mlflow Run Id */
            mlflow_run_id: string | null;
            /** Primary Metric Name */
            primary_metric_name: string;
            /** Primary Metric Value */
            primary_metric_value: number;
            /** Rank */
            rank: number;
        };
        /** PendingApproval */
        PendingApproval: {
            /** Best Experiment Id */
            best_experiment_id: string | null;
            /** Best Metric Name */
            best_metric_name: string | null;
            /** Best Metric Value */
            best_metric_value: number | null;
            /** Budget Usd */
            budget_usd: number;
            /**
             * Gate
             * @enum {string}
             */
            gate: "budget" | "final";
            /**
             * N Invalidated
             * @default 0
             */
            n_invalidated: number;
            /** Pending Specs */
            pending_specs: components["schemas"]["PendingSpecCost"][];
            /**
             * Projected Usd
             * @default 0
             */
            projected_usd: number;
            /** Reason */
            reason: string;
            /** Spent Usd */
            spent_usd: number;
            /** Thread Id */
            thread_id: string;
        };
        /**
         * PendingSpecCost
         * @description M9d: one pending ExperimentSpec's identity plus its PROJECTED cost (foundry/tools/cost.py's
         *     project_run_usd — max(mean completed cost, the spec's own est_cost_usd), never est_cost_usd
         *     alone), for the budget gate's "pending exp-005 lightgbm $2.10" rows (design-plan.md §6). Not
         *     msgpack-allowlisted: it only ever travels inside an ApprovalRequest/PendingApproval dumped
         *     with model_dump(mode="json") for interrupt(), never held directly in FoundryState.
         */
        PendingSpecCost: {
            /** Experiment Id */
            experiment_id: string;
            /** Model Family */
            model_family: string;
            /** Projected Cost Usd */
            projected_cost_usd: number;
        };
        /**
         * RedTeamFinding
         * @description Code-assembled record (foundry/teams/red_team.py) of one RedTeamVerdict plus the
         *     experiment_id it was rendered against — the unit foundry/state.py's `invalidations`
         *     add-reducer accumulates, and what foundry/leaderboard.py filters leaderboard candidates by.
         */
        RedTeamFinding: {
            /**
             * Category
             * @enum {string}
             */
            category: "leakage" | "contamination" | "improper_cv" | "validation_overfitting" | "seed_hacking";
            evidence: components["schemas"]["AuditEvidence"] | null;
            /** Experiment Id */
            experiment_id: string;
            /** Explanation */
            explanation: string;
            /** Recommendation */
            recommendation: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "valid" | "invalidated";
        };
        /** Replay */
        Replay: {
            /** Frames */
            frames: components["schemas"]["ReplayFrame"][];
            header: components["schemas"]["ReplayHeader"];
        };
        /**
         * ReplayDecision
         * @description What the operator did at a gate while the recording was made.
         */
        ReplayDecision: {
            /** Approved */
            approved: boolean;
            /**
             * Gate
             * @enum {string}
             */
            gate: "budget" | "final";
            /**
             * Note
             * @default
             */
            note: string;
            /** T Offset S */
            t_offset_s: number;
            /** Wait S */
            wait_s: number;
        };
        /**
         * ReplayFrame
         * @description `status` is carry-forward ENCODED — it is not a standalone RunStatus. Read it only through
         *     fold_frames() here or foldFrames() in web/src/replay/fold.ts.
         */
        ReplayFrame: {
            event: components["schemas"]["ActivityEvent"];
            status: components["schemas"]["RunStatus"];
            /** T Offset S */
            t_offset_s: number;
        };
        /** ReplayHeader */
        ReplayHeader: {
            /** Budget Usd */
            budget_usd: number;
            /** Decisions */
            decisions: components["schemas"]["ReplayDecision"][];
            /**
             * Duration S
             * @default 0
             */
            duration_s: number;
            final_status: components["schemas"]["RunStatus"] | null;
            /**
             * Gate Wait S
             * @default 0
             */
            gate_wait_s: number;
            /** Goal */
            goal: string;
            /**
             * N Frames
             * @default 0
             */
            n_frames: number;
            /** Name */
            name: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Task */
            task: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** ReplaySummary */
        ReplaySummary: {
            /**
             * Committed
             * @description a shipped demo (replay_demo_dir), not a local recording
             */
            committed: boolean;
            /** Duration S */
            duration_s: number;
            /** Goal */
            goal: string;
            /** N Frames */
            n_frames: number;
            /** Name */
            name: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Task */
            task: string;
            /** Thread Id */
            thread_id: string;
        };
        /** ResumeRequest */
        ResumeRequest: {
            /** Approved */
            approved: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** RunStatus */
        RunStatus: {
            /**
             * Budget Usd
             * @default 0
             */
            budget_usd: number;
            /** Cost By Agent */
            cost_by_agent: {
                [key: string]: number;
            };
            data_profile: components["schemas"]["DataProfile"] | null;
            /** Dataset Ref */
            dataset_ref: string | null;
            /** Error */
            error: string | null;
            /** Experiments */
            experiments: components["schemas"]["ExperimentResult"][];
            /** Goal */
            goal: string | null;
            /** Invalidations */
            invalidations: components["schemas"]["RedTeamFinding"][];
            /** Leaderboard */
            leaderboard: components["schemas"]["LeaderboardEntry"][];
            /** Model Card Md */
            model_card_md: string | null;
            pending_approval: components["schemas"]["PendingApproval"] | null;
            /** Report Md */
            report_md: string | null;
            /**
             * Spent Usd
             * @default 0
             */
            spent_usd: number;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_approval" | "completed" | "failed";
            /** Stop Reason */
            stop_reason: string | null;
            /** Thread Id */
            thread_id: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** StartRunRequest */
        StartRunRequest: {
            /**
             * Budget Usd
             * @default 20
             */
            budget_usd: number;
            /** Goal */
            goal?: string | null;
            /**
             * Task
             * @description bundled dataset registry key, e.g. 'churn'
             */
            task: string;
        };
        /** StartRunResponse */
        StartRunResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_approval" | "completed" | "failed";
            /** Thread Id */
            thread_id: string;
        };
        /** TaskResult */
        TaskResult: {
            /** Approach */
            approach: string;
            /** Calls By Agent */
            calls_by_agent: {
                [key: string]: number;
            };
            /** Config */
            config: string;
            /** Cost By Agent */
            cost_by_agent: {
                [key: string]: number;
            };
            /** Cost Total Usd */
            cost_total_usd: number;
            /** Dataset Ref */
            dataset_ref: string;
            /** Error */
            error: string | null;
            /** First Model Family */
            first_model_family: string | null;
            /** N Experiments */
            n_experiments: number;
            /** N Invalidated */
            n_invalidated: number;
            /** N Successful */
            n_successful: number;
            /** Primary Metric Name */
            primary_metric_name: string;
            /** Primary Metric Value */
            primary_metric_value: number | null;
            /** Stop Reason */
            stop_reason: string | null;
            /** Target Met */
            target_met: boolean;
            /** Target Value */
            target_value: number;
            /** Thread Id */
            thread_id: string;
            /** Wall Time S */
            wall_time_s: number;
            /** Winning Model Family */
            winning_model_family: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_approvals_approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingApproval"][];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOption"][];
                };
            };
        };
    };
    get_eval_results_eval_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResult"][];
                };
            };
        };
    };
    get_replays_replays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaySummary"][];
                };
            };
        };
    };
    get_replay_replays__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Replay"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"][];
                };
            };
        };
    };
    start_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_runs__thread_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiments_runs__thread_id__experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_runs__thread_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
