/**
 * Generates src/api/schema.d.ts from web/openapi.json (which scripts/dump_openapi.py derives from
 * the FastAPI app). CLAUDE.md: types are "generated from FastAPI OpenAPI, never hand-written" — the
 * API's own schema is the source of truth, so a route or model change becomes a TypeScript compile
 * error here instead of a runtime surprise in the browser.
 *
 *   node scripts/gen-types.mjs           write src/api/schema.d.ts
 *   node scripts/gen-types.mjs --check   write nothing; exit 1 if it is stale
 *
 * A .mjs script rather than an npm-script shell pipeline because mktemp/diff are not portable to
 * the Windows shell this repo is developed on. src/api/schema-freshness.test.ts runs the same
 * comparison under Vitest, so drift fails `npm test` and not only a make target someone forgot.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

// import.meta.dirname, not new URL(..., import.meta.url): the freshness test imports this file under
// Vitest's jsdom environment, where import.meta.url is not a file: URL.
const SPEC = resolve(import.meta.dirname, "../openapi.json");
const OUT = resolve(import.meta.dirname, "../src/api/schema.d.ts");

const BANNER = `/**
 * @generated by scripts/gen-types.mjs from web/openapi.json. DO NOT EDIT.
 * Regenerate with \`make types\` (or \`npm run types\`) after \`make openapi\`.
 */

`;

export async function generate() {
  const spec = JSON.parse(readFileSync(SPEC, "utf8"));
  const ast = await openapiTS(spec);
  return BANNER + astToString(ast).replace(/\r\n/g, "\n");
}

async function main() {
  const rendered = await generate();
  if (process.argv.includes("--check")) {
    const current = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : null;
    if (current !== rendered) {
      console.error("src/api/schema.d.ts is stale; run `make types`");
      process.exit(1);
    }
    console.log("src/api/schema.d.ts is up to date");
    return;
  }
  writeFileSync(OUT, rendered, { encoding: "utf8" });
  console.log(`wrote ${OUT}`);
}

// Importable by the freshness test (which calls generate()) without running as a script.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
